### ISSUE TITLE
"Go to New Table" button after a game is completed

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#103]
When a game ends, in the middle bar there should be a button to go to a new table that has the same settings as the current game (password, max players, etc), the room will be created and hosted by the first person to click the button, and the rest will follow. this will be like a remake button which only appears when the game is completed, and serves as an easy way to hop to the next game.

- if the table had a password, those jumping to the next game shouldnt have to re-enter it since they could only be clicking the button if they were in the previous room which required the same password.

**Comment by vck3000** [comment]
Now that we have matchmaking I think the need for this is reduced.
