### ISSUE TITLE
Mod vote/action override

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#120]
Allow the mods to make a game-move (picking a team, app/rej, success/fail, carding*, assassination).
It should be public knowledge when the mod does such an override, and what was done.

*Carding is also necessary in case a losing player who holds the card afks. Either the mod should be told the result or the result should be made public, but its not so relevant because this will only be done in cases where the outcome is obvious and therefore the result will be meaningless. The only time the result might matter is in games where a spy afks, has card, res is about to win and he would have used the card to find oberon, in which case either the mod knowing or everyone knowing are still fine behaviors.

**Comment by vck3000** [comment]
Implemented
