### ISSUE TITLE
Card history display

### ISSUE THREAD

**Issue by vck3000** [vck3000/ProAvalon#123]
Carding history for Lady of the Lake, Ref of the Rain, Sire of the Sea?

A list of usernames would probably be the easiest implementation underneath the vote history table.
e.g. "ProNub -> Bocaben -> Maddie".

If really desired, I guess we can add in the players' alliance claims by reading for "res"/"spy" in the carder's next line of chat.... but this is very extra and could cause mistakes in recording if someone did not mean it...

**Comment by CottageInTheCity** [comment]
I'm no longer in the development server but a while back we had a discussion regarding how to implement card history for Lady of the Lake only. I think that if we have 3 different icons for the 3 different cards, and build on the previous idea (I'll go find it if you drop me an invite link) we can make this work. If you need a better idea I can draft up an image.

**Comment by CottageInTheCity** [comment]
the cloud glyph is first row, third from the right here --- https://getbootstrap.com/docs/3.3/components/

**Comment by CottageInTheCity** [comment]
[card history example 1](https://cdn.discordapp.com/attachments/419756868357980160/523410094218805248/ch-example-1.png)

[card history example 2](https://cdn.discordapp.com/attachments/419756868357980160/523410108693217302/ch-example-2.png)

the key is:

book = lady of the lake
popsicle = sire of the sea
cloud = ref of the rain
green (#2fbd33) = in possession of a card
red (#b00707) = in possession of no cards
light purple in mission x (#ab03ab) = a card moved after mission x.5 resolved
dark purple in mission x (#6b2c6b) = none of the cards moved after mission x.5 resolved

the hex values are open to change, just ideas

**Comment by vck3000** [comment]
Added in e165a63e988b67dcd496e74619fe570c574e3ea3.
