### ISSUE TITLE
When switching rooms, game chat from old room remains

### ISSUE THREAD

**Issue by sidewalkill** [vck3000/ProAvalon#136]
As shown in the image [here](https://cdn.discordapp.com/attachments/516702493963714561/530914421527281694/unknown.png), gamechat from the room I was previously in shows up when I enter a new room. I switched tabs on the proavalon website, and went back to the lobby, but the problem wasn't fixed until I reloaded the page.

**Comment by vck3000** [comment]
Unable to reproduce...
