### ISSUE TITLE
Encrypting and Storing IP Addresses

### ISSUE THREAD

**Issue by chi00** [vck3000/ProAvalon#138]
This feature would allow IP-based disciplinary actions regardless of a user's online status while at the same time maintaining data privacy by encrypting the IP addresses

**Describe the solution you'd like**
It was suggested that hashing and/or salting would work effectively in encrypting IP addresses and after that, store the IP addresses to allow for IP-based disciplinary actions for users regardless of their online status.

**Describe alternatives you've considered**
I can't think of a work-around so far

**Comment by vck3000** [comment]
I wouldn't attempt this unless you really know what you're doing...
