### ISSUE TITLE
Claim button is visible to people who aren't sitting down

### ISSUE THREAD

**Issue by vck3000** [vck3000/ProAvalon#14]
Simple fix that might take some time...

Claim button can have a class "faded" added to it that will fade it visually. 

The following code in buttonEventListener2.js will make it only claim when there is no faded class on the button.
```   
document.querySelector("#claimButton").addEventListener("click", function () {
    //If the button is not faded, then claim
    if($("#claimButton").hasClass("faded") === false){
        socket.emit("claim", "");
    }
});
```
At all times, when a person isn't sitting down at a table, they should have the button faded.
Whenever a person sits down, the button should be unfaded.

**Comment by jezznar** [comment]
I think we are using bootstrap, if so you can just addClass("disabled") and enable it as needed.

**Comment by vck3000** [comment]
I actually have this in the lobby.css. To be honest its not good code and should be improved... but I had trouble with the approve reject buttons displaying, and fading correctly so I found this to be a temporary (and so far stable) solution.

```
.disabled{
    display:none;
}
```

Faded right now only visually fades the button, but doesn't disable. Ideally we should use disabled as you pointed out!
```
.faded {
    opacity: 0.5 !important;
    filter: alpha(opacity=50); /* For IE8 and earlier */
    visibility: visible !important;
    /* display:block; */
}
```

**Comment by jezznar** [comment]
`.disabled{ display:none; }`

I think bootstrap has .hidden for this.
I will try to refactor/review the lobby.css file to see whatelse we can reuse from bootstrap.

**Comment by jezznar** [comment]
I'll take this on hand.
