### ISSUE TITLE
Crash at 14:30 PST, game lost

### ISSUE THREAD

**Issue by Ba3henov** [vck3000/ProAvalon#149]
Second time this happened to me. Game wasn't complete, server crashed, and when we reloged in the game was lost. Interestingly, the other 2 games going on at the time were saved.

**Comment by vck3000** [comment]
Do you have any more details? 

Was it a password protected room? Anything special about roles? Any faded out avatars when they shouldn't be? What was the message when the server crashed? 

Every ongoing game will have a save file stored so no matter what kind of crash, it should always be reloaded. This is the first time I've heard of a game not recovering...

**Comment by Ba3henov** [comment]
Public room, classic roles, I just had everything freeze and couldn't do anything, so eventually I just refreshed the page (which I'm guessing is what happened to everyone else). When I rejoined the lobby, the room was gone.

**Comment by Keleco38** [comment]
I think I was in this one.  For me, i didnt freeze or lag, but every other player that was in the room logged out.   I waited a little bit, then assumed it was a server blip.  I might have tabbed out to the lobby.  I wonder if when the server caught up it figured everyone in the room had left the game, so it didnt reset?

**Comment by vck3000** [comment]
Hmm I'm not sure. If the other rooms were "frozen" when you refreshed that would signal a server restart.

At the moment, a frozen game is only "unfrozen" when 5 players have joined. Once that threshold is reached, when players leave and no one is left in the room, it will close the room. Until it hits that 5 player threshold, leaving the room with no one left will not remove the room. 

I really don't have enough information here to investigate sorry... Good to know that something like this happened though.

**Comment by vck3000** [comment]
I just witnessed a large number of room players being disconnected earlier today with only one or two people left in the room. (I joined right after the glitch happened and came in to see a bunch of leave and join room messages)... I'm thinking it might still be the stats page causing temporary lag (high ram usage). Will investigate.

**Comment by vck3000** [comment]
Should now be solved. The server no longer should crash due to high ram usage when processing stats.
