### ISSUE TITLE
Personal Winrate graph "smushed" in mobile

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#151]
Using galaxy s6

https://cdn.discordapp.com/attachments/483848183601037323/540178646665527320/Screenshot_20190130-163315.png

**Comment by vck3000** [comment]
Difficult to fix that. One solution would be to simply view it on landscape mode. Other than that I dont know what else can be done for that...? (Reduce font and get the user to zoom in? Doesn't seem like a good idea either)
