### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Keleco38** [vck3000/ProAvalon#152]
I have seen this happen a few times.  Occasionally, when I first log in and then enter a room I see an error message in the game chat saying that /roomchat is not a valid command.  None of the other commands work either.  Normally, refreshing the page will fix it and then the game chat loads and commands are recognized.

**Comment by vck3000** [comment]
This happens when one of the server's communication to the client is not received. Normally this doesn't happen and is easily fixed. Perhaps we should add in a prompt saying by default if a command is not recognised to refresh.

**Comment by vck3000** [comment]
Haven't bumped into this issue in a while. I presume must be digital ocean migration related that helped improve it.
