### ISSUE TITLE
Reduce forum spamming by limiting the amount of new threads a user can create per hour

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#154]
If someone has made, say, 3 new threads in the past, say, 6 hours, they should not be able to create any more. This will prevent someone from being able to spam the forum with new threads.

Implementation-wise, store a "rolling" history of the dates of everyone's last 3 new threads posts, and if all 3 are within the past 6 hours, give them an error message that they are above the limit.

The values of 3 and 6 were arbitrarily chosen, but seem to make sense to me as sufficient for preventing spammers while not strict enough to ever hinder legit posters.

**Comment by Keleco38** [comment]
We seem to have a large group of players that misuse the forums, as it's mostly filled with nonsense posts and inside jokes, but I'm not sure I agree with the suggested solution.

Maybe this could be put in place as an interim solution to reduce the spamming but I think the community needs to take a step back, look at forums as a whole,  and decide on a strategy going forward to improve them and make them more relevant.

This could include:

- improvements to the listing ( allow filtering, searching )
- add the ability to tag or group posts by topic,  maybe a separate board for unrelated posts?
- determine (and enforce) community rules for posting. ( maybe add forum moderators, who can help keep the forums tidy? )
 - add the ability to delete posts based on reporting ( ie:  if a post gets reported 10 times by 10 different people,  then mark it as spam (or delete it )?

**Comment by bocaben** [comment]
Please create a new Issue(s) for those suggestions. Those seem like good
ideas, and can be implemented in addition to this Suggestion.

**Comment by Keleco38** [comment]
My point is that we shouldnt implement this suggestion....

**Comment by bocaben** [comment]
It is an easy fix to the annoying job of mods having to manually delete
jerks' spam posts.

**Comment by Keleco38** [comment]
If thats your reasoning, just remove forums entirely...  Heaven forbid we should try to make things work when its easier to just punish everyone for what the jerks do

**Comment by vck3000** [comment]
Fixed in 984a98b157f49ae2169436dc440b2d4690336417
