### ISSUE TITLE
In the middle of the game, a player was demoted to spectator

### ISSUE THREAD

**Issue by Ba3henov** [vck3000/ProAvalon#156]
Had a private room, 8p. All of a sudden we were dc'ed, and when we logged back in one of us only had the option to 'spectate' instead of regular voting options. we couldn't continue the game as a result. He is grandalf and he was morgana this game.
![52115619_619779508467988_3571669600485507072_n](https://user-images.githubusercontent.com/46943437/52932970-88d52080-3306-11e9-8cbf-dbe62d21033c.jpg)

**Comment by vck3000** [comment]
Sorry I don't have enough information about this bug. This is the first time I've seen it. Thank you for reporting it though. If it resurfaces we can reopen this issue.
