### ISSUE TITLE
Games that don't get past M1.1 don't get deleted from database

### ISSUE THREAD

**Issue by vck3000** [vck3000/ProAvalon#16]
On server reload they appear as frozen.
This is probably a problem in the sockets/sockets.js file where I was saving games after each "gameMove".

**Comment by jezznar** [comment]
is the issue about frozen rooms with passwords not being cleared the same issue as this one? if not maybe you can create a checklist. example:
[ ] checklist item 1
[ ] checklist item 2

**Comment by vck3000** [comment]
No, its a similar but different bug. 

The reason frozen games are frozen forever, is because they are checked and deleted when a user **leaves** a frozen room (there is no periodic check for removing frozen rooms). If someone with the frozen room password enters and then leaves a locked frozen game (that has gone past M1.1) it will delete correctly. This can be a made a separate issue. (Solution is to just need to introduce a periodic 5 min or so check for frozen games and remove if too old)

Frozen games that do not make it past M1.1 do experience the bug in this issue though.

**Comment by vck3000** [comment]
Paraphrased info from Hakha:

> A lot of the games that seem to not go past M1.1 actually finish properly. It looks like there may be two savedGame records being created, and only one being deleted at the end of a game.

**Comment by vck3000** [comment]
I think I've found the cause. Writing this here so I can find it later.

```
			savedGameObj.create({room: jsonifiedRoom}, function(err, savedGame){
				if(err){
					console.log(err);
				}
				else{
					rooms[rooms.indexOf(roomToSave)].savedGameRecordId = savedGame.id;
					// console.log("Successfully created this save game");
					
				}
```

The line `rooms[rooms.indexOf(roomToSave)].savedGameRecordId = savedGame.id;` is likely the issue. What is happening is that a save game is being created, but that saved game does not have the ID of itself stored in it. So the next time it is loaded, and tries to delete itself, it doesn't have a save game ID to delete. The solution would be to when the game is loaded, set the savedGame.id to it when reloading it.

**Comment by vck3000** [comment]
Should be fixed now. Will reopen if it happens again.
