### ISSUE TITLE
mute specs during assassination

### ISSUE THREAD

**Issue by Keleco38** [vck3000/ProAvalon#160]
Listen, it is a well known fact that long assassinations can be boring as heck, especially for specs waiting to join the next game.  But, that doesnt give you permission to 'help' the spies in order to speed things up ( or to lighten the mood, or troll, or make a joke). 

We can politely ask specs to be quiet, but for one, they rarely listen, and two, it can be a tell since its normally only res doing the complaining.

Since it seems most spectators cant respect the game, I suggest that game chat should be limited to only those within game (res and spies) during the assassination phase.

**Comment by vck3000** [comment]
Need a concensus on what is to be implemented.
