### ISSUE TITLE
Settings Modal Broken in IE

### ISSUE THREAD

**Issue by Keleco38** [vck3000/ProAvalon#161]
**Describe the bug**
The settings modal initially renders correctly in the IE browser but displays blank content when you click on any of the left hand links.

**To Reproduce**
1. Log in to the site using IE. ( I have IE edge, but also tried it emulating IE 9)
2. Click on the settings gear icon to open the modal dialog
3. Click on any of the links on the left side
4. Note the blank screen

**Comment by vck3000** [comment]
Windows' supported browser is now Microsoft Edge. IE will not be supported on this site.
