### ISSUE TITLE
Log in/ Gameplay identity verification mismatch

### ISSUE THREAD

**Issue by throwaway0164** [vck3000/ProAvalon#163]
Log-in isn't case sensitive for username, playing the game is. I was originally logged in as Thor, but the browser crashed. I could log in as thor, but can't actually play the game. I have to log in as Thor to play the game.

**Comment by vck3000** [comment]
This is intended. Login case insensitive allows for users to set whatever case they wish. Case sensitive during games helps keep consistency - and also helps avoid impersonations of other players.

**Comment by Keleco38** [comment]
If this is intended then it's poor design.   I can understand why it's a won't fix at this point in time, but future refactoring should take a look at the authentication implementation.   Games should be tied to the logged in user account and not to the usename as it was typed in for the current session.   Or, you allow someone to authenticate case insensitve but then use the usename as it appears in the database, for whatever mechanism is in place to persist the login.

**Comment by vck3000** [comment]
All non-game usernames are checked with the lower cased version. If there is anywhere that doesn't make this check let me know please.

**Comment by Keleco38** [comment]
I dont think thats the issue though.   What I don't understand is why someone can get disconnected and that 'loses' the association with an inprogress game.  Buddy can login, he can edit his account, view his stats,  but he can't rejoin the game he is legitimately playing.   Something if off with the way the game gets linked to the account.   But, I will let you know if I can see anything when I get back to looking at the code.

**Comment by vck3000** [comment]
Tify and TIfy shouldn't be able to play the same game. It can be confusing for players.

**Comment by Keleco38** [comment]
huh?

say you have a game with players  A, B, C, D & E
there is some issue that causes A to disconnect. In his rush to get back into the game,  he logs in again as a.    He should be able to get back into the game.    A and a wouldn't be playing the same game?

I think a better fix would be that  if  a user joins and sets his username to be AbCd,  then when he logs in  he should always get logged in and appear as AbCd,  no matter what case he used in the sign in form.
