### ISSUE TITLE
New /guessmerlin <name> command

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#173]
Solely for fun, during the assassination, allow people could make guesses with some sort of "/guessmerlin <name>" command. after the assassination, people's guesses will be shown.
Perhaps we could also send the guesser a server message saying if they were right or not
so if someone is bored of the game and is just waiting around to see the result, they can make a guess, start a new game, and then will get the results of the shot sometime after.
Nobody will know who, if any, have officially locked in guesses until after the shot.
Probably shouldn't be recorded anywhere either - it'd just be for 'bragging rights'.

**Comment by vck3000** [comment]
Interesting. Shouldn't be too d difficult to implement.

**Comment by vck3000** [comment]
Fixed in #176.
