### ISSUE TITLE
possibility to highlight all chat to yellow +  possibility to unhighlight all the players

### ISSUE THREAD

**Issue by tonymarkoc** [vck3000/ProAvalon#18]
Enchantment:

1) Blue, red, green colors are not really eye-friendly and they are hard to read in chat. Add the possibility to change highlight color to yellow with the single click (like on theresistanceplus.com)

https://www.proavalon.com/forum/show/5b73d5fbd7ff62001450d6e4

2) Add the possibility to unhighlight all the players. Sometimes we just want to unhighlight all the players --> new game, or the end of the game, or maybe in the middle of the game if we want to reset all of our highlighted colors because we changed our merlin/spy/percy decisions.

https://www.proavalon.com/forum/show/5b73d575d7ff62001450d6e3

created 2 pull requests

**Comment by tonymarkoc** [comment]
#17 Fixed in this pull request

**Comment by vck3000** [comment]
Fixed in #17
