### ISSUE TITLE
Reworking the Nav-Bar

### ISSUE THREAD

**Issue by CottageInTheCity** [vck3000/ProAvalon#188]
Instead of currently having Lobby, Rules, etc. up the top, and continuously adding new places to go as we create them (eg. skies' community page), we create drop down menus with multiple options, based on similarities between the pages. Something like this, for example;

**Games**

- Lobby
- Rules
- Stats

**Community**

- Members _(a rename for the page skies made)_
- Forums
- Facebook

**Development**

- About
- Log
- Github

These are open to change but just what I thought made the most sense

**Comment by AndrewCutler** [comment]
Hello, I would be glad to work on this if you'd like.

**Comment by vck3000** [comment]
That would be great! I think for now keep lobby, rules and stats as separate navbar buttons. 

Other than that looks good!

**Comment by AndrewCutler** [comment]
![navbar dropdown](https://user-images.githubusercontent.com/41751000/58123885-df3e4d80-7bda-11e9-9255-417348a02b2d.png)

Forums and Facebook links are under the Community dropdown of course. The dropdowns are present for the mobile version under the hamburger menu too -- do you think it's better they be expanded out?

**Comment by vck3000** [comment]
Could you please provide a screenshot of the mobile view? Dropdown buttons that have the little triangle (or carat I think) in the hamburger menu should be good! Might be best to keep things consistent if possible!

**Comment by AndrewCutler** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/41751000/58133627-474c5e00-7bf2-11e9-8e18-7f8b0a3b7e0d.png)

**Comment by vck3000** [comment]
Hmm, that's a difficult one. I still think maybe default collapsed might be better. Default expanded might look a bit cluttered with the massive navbar.

**Comment by AndrewCutler** [comment]
Sorry, maybe I misunderstood. The screenshot I provided is after clicking the hamburger dropdown. This is the mobile navbar by default (collapsed):
![Screenshot (36)](https://user-images.githubusercontent.com/41751000/58134901-56cda600-7bf6-11e9-98ad-bed4ff44e1f9.png)

Clicking the hamburger menu drops down the navbar links, pushing the body content down as normally (shown in previous comment).

**Comment by vck3000** [comment]
Yeap. By default, the whole hamburger menu is collapsed. Clicking the hamburger will open the navbar.

What I mean above was when the hamburger is clicked, the individual dropdowns (community and development) should probably be collapsed still, and require another click to open them up. 

Does that sound reasonable? Or do you think the insides of community and development should be expanded by default?

**Comment by AndrewCutler** [comment]
Nope, I think they should also be collapsed by default. That's their current behavior; both collapsed when you open up the menu.

**Comment by vck3000** [comment]
Closed in 16fb0cb35de4b3c27316d9ffe6c570769bffda46
