### ISSUE TITLE
Claiming what alliance is the carded player

### ISSUE THREAD

**Issue by ayywaz** [vck3000/ProAvalon#202]
I think this feature would be interesting when analyzing data. Also, it would help specs to familiarise themselves with the game quicker. And it shouldn't be too hard to implement.

Also, it could auto-correct the claim if you are res.

**Comment by vck3000** [comment]
The harder thing to implement is HOW the user will input what they would like to be claimed. Chat can't be relied upon (as in searching for the first spy or res keyword). The best system I can think of is a pop up box with 
              CLAIM: 
            Res    SPY

buttons. But the other issue is how much to "influence" the game. Some people already dislike the CLAIM button. I don't know if it is proper to implement this. From a data perspective, it would be very helpful though. Needs more discussion from community.
