### ISSUE TITLE
Dark mode only works in lobby

### ISSUE THREAD

**Issue by pi-guy-in-the-sky** [vck3000/ProAvalon#209]
**Describe the bug**
If a user selects dark mode in their settings in the lobby but then navigates to a different page, the new page is no longer in dark mode.

**To Reproduce**
1. Go to `/lobby`
2. Click on the cog/settings icon in the navbar
3. In the pop-up, select "Dark theme"
4. Close the menu and navigate to a different tab
5. The page is no longer in dark theme

**Expected behavior**
After checking dark theme in the lobby, I expected the settings to work for the entire site.

**Screenshots**
![Screen Shot 2019-07-10 at 23 32 26](https://user-images.githubusercontent.com/36142229/61024485-06a7d000-a36b-11e9-9ddc-b58fffa019bd.png)

![Screen Shot 2019-07-10 at 23 32 31](https://user-images.githubusercontent.com/36142229/61024491-0b6c8400-a36b-11e9-94fe-34e784dc417a.png)

![Screen Shot 2019-07-10 at 23 32 36](https://user-images.githubusercontent.com/36142229/61024510-16bfaf80-a36b-11e9-9918-10e561662544.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Google Chrome
 - Version: 75.0.3770.100

**Additional context**
I think this problem could be easily fixed by moving dark themes into the header, or using something like [bootswatch](https://bootswatch.com/) for a color scheme and replacing it in the header if dark mode is enabled.

**Comment by vck3000** [comment]
At the moment, the "settings" options are only implemented on the `/lobby` route. I think a good solution for site-wide dark theme, would be to import the settings to all pages requiring log in. I'm unsure how I would approach this however. Perhaps throw the whole settings code into the `partials/header.ejs` file? Maybe also have a condition to check whether the user is logged in.

**Comment by vck3000** [comment]
Closed in #214.
