### ISSUE TITLE
Tutorial for new accounts

### ISSUE THREAD

**Issue by Keleco38** [vck3000/ProAvalon#215]
I suggest we add a short welcome tutorial or set of help screens and force new accounts to at least cycle through them before they enter the lobby the first time.

It could just be one or two screens with common rules and suggestions.  i.e. how to contact mods, where the link to discord server is,  pointing out that chat is important and make sure you look at it during game and dont be afraid to participate.  It could also suggest the golden rules etc...

We just had a game with a new player who was silent and didnt seem to be following chat.  Now, some cynics might immediately suggest he was trolling, but I would like to give them the benefit of the doubt and think that he was just new and didnt know what he was doing.  Forcing new players to go through a short tutorial might help get them up to speed more quickly.

**Comment by vck3000** [comment]
This feature would take a long time to implement. The larger our player base becomes, the more this will be needed.

**Comment by jani-hautamaki** [comment]
Tried and felt that a llot friendlier atmosphere is needed. Maybe a different section for people who just want to play for fun? No kicking and so forth...

**Comment by jani-hautamaki** [comment]
Just to note. I think this has reached the critical mass. There's no way to make it bigger than it is with its current state.

**Comment by vck3000** [comment]
I guess you're suggesting it's time for a tutorial for newer players?

**Comment by vck3000** [comment]
Probably not worth it. There can be other ways we assist newer players.

**Comment by jani-hautamaki** [comment]
lol. Sure :)
