### ISSUE TITLE
Required # of games to talk in all chat/spectator

### ISSUE THREAD

**Issue by morningcatt** [vck3000/ProAvalon#223]
Hello this is Catt. I think this will reduce spamming if we have a buffer for new players on these fronts. Maybe in private games you can talk without a buffer but it may be good to have a 5 games to talk in all chat, 7 to talk as a spectator or something like that. If someone really wants to ask if the person talks / can they play, if they are seated they can answer.

**Comment by vck3000** [comment]
Please discuss this in the moderator chat and let me know of your consensus.
