### ISSUE TITLE
VPN Blocking

### ISSUE THREAD

**Issue by morningcatt** [vck3000/ProAvalon#224]
Gonna be real with you, idk how this works or how to do it.

**Comment by AwfulProgrammer** [comment]
Typically if you want to block VPNs, you'd have to block ip addresses associated with VPN usage. There really isn't any way to specifically target VPNs as far as i'm aware, so you'd have to go around finding popular VPN addresses and start blocking from there.

**Comment by vck3000** [comment]
Closed in 07f8d640cbe3a92135603a128ee3018410902fad.
