### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by resskies** [vck3000/ProAvalon#28]
I randomly disconnect every 10 minutes on laptop. I instantaneously disconnect if I switch to Discord app on phone.

**Comment by vck3000** [comment]
What browser is your laptop running? Do you have any power saving features turned on? PC's shouldn't normally dc if the tab is open.

Same question for phone, what browser and any power saving features on? What brand of phone? (Most phones will automatically disconnect your connection to the server if you aren't using it, i.e. looking at discord to ensure your phone doesn't slow down).

**Comment by resskies** [comment]
Chrome. No I’m on full power and it disconnects very frequently. Same for phone, I stopped playing on phone because it doesn’t allow multitasking anymore.

**Comment by jezznar** [comment]
@vck3000 i think it'll be better if we could put a small timer before declaring the user as disconnected. But yeah, overall a reconnection algo will be great.

**Comment by vck3000** [comment]
If you can find where that timer is within the sockets.io library then go for it lol
