### ISSUE TITLE
Restart the game! 

### ISSUE THREAD

**Issue by Sowmith-iiit** [vck3000/ProAvalon#304]
**Restart the game in a given room.**
It is tedious and frustrating to go the lobby create another room share the room number and password with your bunch of friends (or any private circle). 

**Describe the solution you'd like**
A restart button which re-starts the game with the same set of characters initially chosen as default. But the host should be able to change if he would like to.

**Describe alternatives you've considered**
You could at least have the option of restarting the game for password protected rooms because they clearly are playing with a private set of people.

**Comment by vck3000** [comment]
Hi there,

This idea has been floated around previously and we do plan on implementing this. However at the moment there are more pressing issues with the server, and we are actively developing a new re-write of the site. Unfortunately we don't have the resources to implement this just yet. If you are interested in contributing, please let me know and we can get you involved!

**Comment by Sowmith-iiit** [comment]
Sure. I am interested in contributing. Do let me know if you want to chat about it sometime.

**Comment by vck3000** [comment]
Sure, flip me an email at admin@proavalon.com or a discord message to pkvk9122 #6596 :).
