### ISSUE TITLE
Player gets disconnected.

### ISSUE THREAD

**Issue by Sowmith-iiit** [vck3000/ProAvalon#305]
**Describe the bug**
People get disconnect way too often during the game. 

**To Reproduce**
- Play the game for some time may be during high traffic periods. Was not happening initially but happened way too many times in the last two set of games.  

**Expected behavior**
https://github.com/vck3000/ProAvalon/pull/141 - Does clicking the danger icon gets us back into the game or the lobby ?

Refreshing the page because lost connections leads to going to lobby again (as the room is not mapped to any url, one fix could be to at least map the room with some url so that people can just refresh.) May be store information about the session in cookies and try to take him to the room when disconnected. 

If we could make the disconnection go away by changing something, that would be epic. [](url)

**Desktop (please complete the following information):**
 - OS: Mac, Linux, Windows
 - Browser : Chrome
 - Version : 80.0.3987.163 (Official Build) (64-bit)

**Comment by vck3000** [comment]
Hey!

This is a big issue with the current site. We are working on a multi-server approach for load balancing in the next re-write of the site. We did not expect such a high influx of new users on the site and definitely was not prepared for it. If you would like to help out writing the new website, let us know and we would be happy to have you help!

**Comment by vck3000** [comment]
We've added in a auto-reconnect feature. Hopefully this fixes this.
