### ISSUE TITLE
Profile stats: Add an option to display as table or graph

### ISSUE THREAD

**Issue by jezznar** [vck3000/ProAvalon#32]
When browsing through the profile area, I cringe a lot when I see the json object at the bottom. I think it will be better if there is an option to show the data in tabular or graphical form.
![image](https://user-images.githubusercontent.com/13676977/45313199-c0be8780-b560-11e8-893f-75e5367603a3.png)

**Comment by vck3000** [comment]
That data is the raw data shown in the graph lol. It's for people who want to extract raw data or for those who want to see how many losses they have (if you have no wins u cant hover over the bar graph because your win rate is 0%).

**Comment by vck3000** [comment]
You could fix the issue of not being able to hover over 0% win rate if you'd like :).

**Comment by jezznar** [comment]
>It's for people who want to extract raw data
It's a good practice to create a separate api which will serve raw data to any integrator (i.e. https://this.site/api/v1/playerdata/playername). Usually, All data in the frontend should be presented in a well-perceived visualized manner (i.e. visualizing json data as graphs/tables) and should do away with displaying raw json data :) but yeah, your call.

what do you think about maintaining the graph right there and transforming the json data into a table and put it right beside it? This way, we don't have to fix the hovering of 0% and when they see the table, they will realize that the reason why they can't hover is because they have 0% in that field.

**Comment by vck3000** [comment]
People can hover over the bar to see all the data the raw json provides, so having an extra table is quite redundant as the only real use would be to see total losses and all the numbers of games... I'm a bit worried it might look bad but if you can make the table look good then go for it lol. Otherwise we can just remove the raw json display at the bottom, it's not important.
