### ISSUE TITLE
Add possibility to hide your stats

### ISSUE THREAD

**Issue by tonymarkoc** [vck3000/ProAvalon#35]
Add boolean on your profile page saying if your profile should be publicly visible or not.

**Comment by vck3000** [comment]
And what specific info should be hidden if it is not publicly visible? Just the graph?

**Comment by tonymarkoc** [comment]
Numbers, everything except the Description (bio) i guess

**Comment by vck3000** [comment]
I feel like the individual breakdowns are ok to hide, but I don't know if hiding the general stats (e.g. total games played) is worth hiding. I think we need more discussion on this.

**Comment by tonymarkoc** [comment]
Why is this closed? I personally want to hide my stats, especially my win rate.
Reason for this is that a lot of player get more toxic if they lose because their win rate drops and they blame others (newbies) more when they mess up the game (guilty).
For the sake of better games (more peaceful), , this would be a nice functionality.

**Comment by vck3000** [comment]
Closed because this needs more discussion. Need a overall decision from the community, not half yes half no.

**Comment by tonymarkoc** [comment]
This is also kinda a matter of privacy, people should be in charge of their profile and what to show what not

**Comment by tonymarkoc** [comment]
I can't believe this is still not considered. I'm thinking about to stop playing because the games are more toxic, because they are more competent. Add unranked games if you don't wanna hide stats, but something here must be done.

**Comment by hakha3** [comment]
games are more competent?

by games being toxic you mean that you become toxic, because you care about stats and if you could hide your stats or play unranked u would be less toxic
or that others are toxic, because they care so much about their stats and if they could just hide it or play unranked they would be less toxic?

**Comment by tonymarkoc** [comment]
@hakha3 correct

**Comment by vck3000** [comment]
1) As I've said, need more input from others. But tbh if you made it I would accept a PR for this. 

2) I don't have time rn to make that feature. Ideally people can help contribute.

**Comment by tonymarkoc** [comment]
Fixed in the pull request #90 
Commented out console.log function that are exposing data even if visually we can't see that div.
Also we are not returning XHR stats data if the user has set the boolean to false.
Added new property on user object.

**Comment by vck3000** [comment]
Closed in #ae402bf0d253cd83bf049cb4b3fbf3b94d7c0ea1
