### ISSUE TITLE
Proavalon Glossary

### ISSUE THREAD

**Issue by richardscollin** [vck3000/ProAvalon#371]
I recently started playing avalon on proavalon.com. I have a couple feature ideas that I'd like to implement, but I see that you're actively developing a new branch. I'm wondering where I should land those patches before I start working. Especially if I'd actually like to see the changes integrated in within a reasonable time frame. Possibly both master and newPA?

I mainly want to integrate the proavalon glossary into the UI somehow. I'm familiar with avalon, but online players use a lot of jargon that I hadn't seen before I think being able to quickly look up terms would be useful. It could even be implemented as a chat command, but I think that a tab in the UI would be better for new players. What do you think?

We can pull the definitions from https://www.proavalon.com/forum/show/5de6ea62b942c600040c215b

**Comment by vck3000** [comment]
Hey richardscollin. Could you please add me on Discord and we can further discuss there? My tag and id is: pkvk9122 #6596. 

The site rewrite is almost at the stage where something like this can be implemented, however discussion needs to be done on whether this is a required feature and how to best integrate it into the site. We have a developer team channel which I can invite you to if you add me on Discord.

**Comment by vck3000** [comment]
Closed in #414.
