### ISSUE TITLE
the cursed and forbidden m2.6 (Sire of the Sea runs after hammer reject)

### ISSUE THREAD

**Issue by sleepyfoxen** [vck3000/ProAvalon#403]
![image](https://user-images.githubusercontent.com/15024086/130370313-085bb87c-ea90-46aa-be34-3221c13604f8.png)

rare and secret mission proposal

---

**Describe the bug**
Sire of the Sea can be used after a hammer reject occurs, allowing the game to continue with the next mission proposal.

**To Reproduce**

i'm not really sure what's the minimum required for this, but for me the most reliable way to trigger it is:

1. start a (bot) game, i use 5p and put all the cards in.
2. fail m1
3. reject m2 hammer. if you're playing with simplebots and you only control 1/5 votes it might take a few tries with bad luck.
4. sire of the sea is used and the game continues, apparently with the next proposal 'replacing' the last

**Expected behavior**
the game should end after a hammer reject

**Screenshots**
here is a case where the hammer was rejected 'twice' with Sire being used after m2.5 gets rejected
![image](https://user-images.githubusercontent.com/15024086/130370020-35c678c6-75ff-40be-add2-697d938e6c05.png)

and here's a case were we got to play on for a bit since m2.6 got approved             
![image](https://user-images.githubusercontent.com/15024086/130370402-0bae1d1a-530a-440f-98e0-54efba9c77e8.png)

**Additional context**

* sorry about the weird theme in the screenshots
* whereas [lady](https://github.com/vck3000/ProAvalon/blob/3116cd50f529e86eaf78a1858789fbc98550bc5a/src/gameplay/avalon/cards/lady%20of%20the%20lake.js#L53) and [ref](https://github.com/vck3000/ProAvalon/blob/3116cd50f529e86eaf78a1858789fbc98550bc5a/src/gameplay/avalon/cards/ref%20of%20the%20rain.js#L62) have specific checks for this case, i don't see the same [in the sire code](https://github.com/vck3000/ProAvalon/blob/3116cd50f529e86eaf78a1858789fbc98550bc5a/src/gameplay/avalon/cards/sire%20of%20the%20sea.js#L57). that's probably why lady and ref don't get used beyond m1 in that last screenshot there, whereas sire does.

**Comment by vck3000** [comment]
Thanks for the bug report. Looks like you've correctly found the bug in that logic. The current structure has duplication across those three files, making it easy to forget to add checks to all of them, and likely what caused this discrepancy. If you'd like to throw up a PR to include the check, I'd be happy to merge it in. In the future, we should migrate to an inheritance model for these kinds of things.
