### ISSUE TITLE
Improve Highlighting contrast in Dark Mode

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#51]
In dark mode, most of the highlights are downright dizzying and make the text unreadable.

**Comment by vck3000** [comment]
A new set of options for dark theme colours?

**Comment by vck3000** [comment]
I'm a bit confused... could you show an example pic?

**Comment by bocaben** [comment]
![image](https://user-images.githubusercontent.com/2280966/50173580-99feb280-0300-11e9-8592-c33ea56d3ed3.png)

**Comment by bocaben** [comment]
also this:
![image](https://user-images.githubusercontent.com/2280966/50174802-cb2cb200-0303-11e9-970d-e6a1608ef9b5.png)

**Comment by vck3000** [comment]
Ah I see
