### ISSUE TITLE
After clicking the = icon by an avatar the icon should change colors

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#53]

**Comment by bocaben** [comment]
I think this was attempted to be closed. however there is a bug, where it stays highlighted after the user clicks "Unhighlight All Chat"

**Comment by vck3000** [comment]
Ah, I'll look into it!

**Comment by vck3000** [comment]
Fixed in d3b1fc45b312bac6b59236081e414242668055ce and f575605d47f96de6abd2a463f106bed9bac4c3ed
