### ISSUE TITLE
Improve [ quoting feature

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#57]
1) Some validation to trigger Quoting should include:
- Did this person actually say it? (but still allow for the quote to be taken mid-sentence)
- Was it at that time? (but take timezone differences into account) 

2) Make the quoted text a color more distinguished than grey. perhaps a light/faded purple? turquoise? something pastel and non-intrusive.

3) Currently including a [ deletes everything typed before it.
ex:
Guys, why did hak shade me in m2.3?? I'm conf res! [18:09] hakha3: uhh boca is probably a spy

BECOMES
[18:18] bocaben: Quoting:
_[18:09] hakha3: uhh boca is probably a spy_

BUT SHOULD BE
[18:18] bocaben: Guys, why did hak shade me in m2.3?? I'm conf res! Quoting:
_[18:09] hakha3: uhh boca is probably a spy_

**Comment by jezznar** [comment]
Also i noticed that you can create a quote that hasnt really been said at all just by putting [ in the chat then fabricate your message after.

**Comment by bocaben** [comment]
I covered that in (1.a)
