### ISSUE TITLE
Timer glitch in half-hour or 45-minute time zones

### ISSUE THREAD

**Issue by QuinnWuest** [vck3000/ProAvalon#596]
**Describe the bug**
If the system's time zone is set to one that is not an hour's interval apart (e.g. UTC +9:30 Adelaide), the timer will display incorrectly, and will be off by 30 minutes.

**To Reproduce**
Set your system's time zone to one such time zone.

Initially reported by Anji.

**Comment by kev306** [comment]
Hi QuinnWuest, the display bug should now be fixed. Please check on your end when you login next
