### ISSUE TITLE
Claiming seems to impact other claims

### ISSUE THREAD

**Issue by vck3000** [vck3000/ProAvalon#618]
Few bug reports from members of the community stating that player A's claim will force player B to claim/unclaim which is weird. 
Requires some investigation.

**Comment by QuinnWuest** [comment]
The "claim" button seems to be connected to every player, only one person can claim at a time, and anyone can unclaim another claimed player.

**Comment by kev306** [comment]
Closed in fa0ce5e49adaffbf6d28edb3108959c0e6f51430
