### ISSUE TITLE
Not being able to select team, when someone joins room

### ISSUE THREAD

**Issue by hakha3** [vck3000/ProAvalon#65]
**Describe the bug**
When player selected team, "PICK" button is clickable, but if meantime someone new joins room or leave it, "PICK" button becomes disabled.

**To Reproduce**
1. Select correct number of players on team
2. Someone else need to join/leave room (prolly it works only with spectators)
3. You cant anymore pick team which you selected (you need to deselect someone and select again)

**Expected behavior**
People coming/leaving to room should not affect "PICK" button

**Comment by jezznar** [comment]
Does this happen everytime? I tried to replicate it during a game earlier, I wasn't able to experience it.

**Comment by hakha3** [comment]
hmm I cant replicate it now as well but I remember having this bug previously

**Comment by vck3000** [comment]
Thanks hakha, that last comment about it only happening with the team leader help me find the bug in the code!
