### ISSUE TITLE
Broadcast to moderators whenever there is a /mcompareips match

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#67]
instead of having to run the cmd periodically, the mods should be alerted (via message from server) when someone logs in while another user from that same ip is already logged in.

additionally, mods who just log in should also receive an alert of all the matched ip that happened while he was away, as well as a way to view a history/log of all matched ips in the past.

**Comment by jezznar** [comment]
About having the same IPs, what about colocated people who play at the same place? How are we supposed to differentiate?

**Comment by bocaben** [comment]
We can't differentiate, but when there's a hit we'll at least be able to investigate. I'll usually ask them directly if they know anyone at the table.

**Comment by jezznar** [comment]
I think this should be split to 2 different issues.
1. Broadcast to moderators whenever there is a /mcompareips match (no need to make a new one, we can stay here) - Quality of Life
2. Create match history log that can be viewed publicly - New Feature

**Comment by bocaben** [comment]
Sure, but it definitely shouldn't be publicly viewable. Should be mods only.

**Comment by bocaben** [comment]
Created issue #70 to for the log feature
As mentioned there, #70 would be redundant if in this feature (#67), the server were to leave mods a notification in addition to a chat broadcast,
