### ISSUE TITLE
Add Site Traffic Statistics

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#68]
Show somewhere stats about the site's daily or weekly traffic trends, like:
- Total Unique Player Logins
- Total Games Finished
- Total Game Hours (for each game, <game length>*<num of players> )

**Comment by vck3000** [comment]
Unique player logins are just the logins? Or unique players who played at least one game during the time period?

**Comment by bocaben** [comment]
I was thinking unique players who have entered the lobby. But unique players who have played at least one game is interesting, possibly even more so.

**Comment by vck3000** [comment]
Games played per day done in b589e0c286d3d4f7dd092900cf9d51a746b041d6
