### ISSUE TITLE
Player's pick phase skipped when he becomes a player and a spectator at the same time

### ISSUE THREAD

**Issue by jezznar** [vck3000/ProAvalon#69]
**Describe the bug**
Not quite sure how this happened but a player can become a spectator at the same time. This results to his pick phase being skipped

**To Reproduce**
*Unclear. Needs more information

**Expected behavior**
someone should not be able to be a player and a spectator at the same time.

**Screenshots**
![pic](https://cdn.discordapp.com/attachments/483848183601037323/489615825020649472/unknown.png)

Room chat log:

> [04:19] Game started with: Merlin, Percival, Assassin, Morgana.
> [04:19] sidewalkill: oh it worked
> [04:19] exmag: How is he still
> [04:19] exmag: A spec
> [04:19] Chaos22 has picked: skies, Chaos22.
> [04:19] exmag has left the room.
> [04:19] pmoomm: yo boi vt
> [04:19] skies: Pick one accuse one or I autospy uou
> [04:19] freshererer: ok i pick myself and accuse 2 of the other 5 people on the board
> [04:19] bb: You are a Resistance. Your role is Spectator.
> [04:19] exmag has joined the room.
> [04:19] freshererer: is that how this works
> [04:19] skies: No pick someone
> [04:19] bb: LMAO I'M GREY
> [04:20] exmag: He's also a spec
> [04:20] sidewalkill: LMAO
> [04:20] skies: On ur pick
> [04:20] freshererer: hahaha
> [04:20] skies: Hahaha
> [04:20] Chaos22: Hahaha
> [04:20] exmag: In another room
> [04:20] sidewalkill: who does chaos accuse
> [04:20] Mission 1.1 was rejected.
> [04:20] Chaos22: ?
> [04:20] sidewalkill: skies has some new rule
> [04:20] freshererer: BB IS OMNIPRESENT
> [04:20] sidewalkill: she wants you to pick someone and spy someone
> [04:20] pmoomm has picked: freshererer, bb.
> [04:20] sidewalkill: LOL
> [04:20] skies: Poom is a spy
> [04:20] pmoomm: haha
> [04:20] skies: Chaos is a spy
> [04:20] sidewalkill: LMAO
> [04:20] bb: Holy shit
> [04:20] skies: I’m not picking poom or chaos
> [04:20] Chaos22: Okay I picked skies and I spy skies (temporarily)
> [04:20] bb: Skies is resing me
> [04:20] sidewalkill: LMAO
> [04:20] bb: That's pretty cool
> [04:20] sidewalkill: bb
> [04:20] Mission 1.2 was rejected.
> [04:21] sidewalkill: why r u a spec
> [04:21] skies: Ok chaos isn’t a spy
> [04:21] sidewalkill: im laughing
> [04:21] bb: IDK
> [04:21] bb: MAYBE I DIED
> [04:21] skies: Poom is a spy
> [04:21] sidewalkill: idk how to do this
> [04:21] bb: I'm a ghost now
> [04:21] sidewalkill has picked: skies, sidewalkill.
> [04:21] pmoomm: i accuse one of bb/fresh
> [04:21] pmoomm: okay??
> [04:21] sidewalkill: ill spy bb?
> [04:21] sidewalkill: i dont know?
> [04:21] bb: Spoooooooky 👻👻👻
> [04:21] skies: Ur too old bb
> [04:21] freshererer: spooky avalon
> [04:21] sidewalkill: spooky avalon
> [04:21] freshererer: ah fuk u beat em
> [04:21] freshererer: me
> [04:21] freshererer: *
> [04:21] bb: Am spooky
> [04:21] Mission 1.3 was rejected.
> [04:21] sidewalkill: bb being a spec is better than skies's stupid new meta
> [04:21] freshererer: oh i thought
> [04:21] freshererer: i was on that
> [04:21] skies: Oh it’s not a new meta
> [04:21] freshererer: im too distracted by spooky bb
> [04:21] sidewalkill: LOL
> [04:21] bb: Spec meta is high elo
> [04:22] skies: It’s a test to find a new meta
> [04:22] sidewalkill: wtf
> [04:22] Chaos22: Test what?
> [04:22] sidewalkill: if i was going to be a lab rat
> [04:22] sidewalkill: i'd make an alt..
> [04:22] skies: Offpicking is a boring meta
> [04:22] freshererer has picked: freshererer, bb.
> [04:22] Mission 1.4 was rejected.
> [04:22] morningcatt has joined the room.
> [04:22] morningcatt: r u winning
> [04:22] sidewalkill: fresh accuse me
> [04:22] morningcatt: offpicking is deliciosu
> [04:22] freshererer: i accuse poom
> [04:22] skies: Fresh accuse someone
> [04:22] sidewalkill: LOL
> [04:22] freshererer: !
> [04:22] skies: Ok
> [04:22] Chaos22: Pick me the only one who hammer bribed
> [04:22] sidewalkill: i cant even remember
> [04:22] sidewalkill: who everyone accused
> [04:22] bb: Pick two spies
> [04:22] sidewalkill: also chaos 1.3
> [04:22] morningcatt: i spy side
> [04:22] sidewalkill: eat ass
> [04:22] freshererer: guys
> [04:22] pmoomm: imagine saying im both res with fresh and bb
> [04:22] pmoomm: cant relate
> [04:22] freshererer: i believe
> [04:22] skies has picked: skies, freshererer.
> [04:22] freshererer: i may
> [04:22] bb: lolol
> [04:22] exmag: How is bb still a spy wtf
> [04:22] freshererer: have to leave
> [04:23] skies: I accuse fresh
> [04:23] exmag: SPEC
> [04:23] sidewalkill: LOL
> [04:23] sidewalkill: wtf r u doing
> [04:23] bb: Am spec and spy
> [04:23] morningcatt: skues is res
> [04:23] Chaos22: Side do not be rude.
> [04:23] freshererer: yeah guys
> [04:23] freshererer: i do
> [04:23] sidewalkill: chaos this is the stupidest game ive ever seen
> [04:23] freshererer: have to leave
> [04:23] bb: Skies your meta is painful to watch
> [04:23] sidewalkill: ^^
> [04:23] freshererer: if u wanna wait 5 mins u can
> [04:23] bb: and participate in
> [04:23] morningcatt: rmk ur not that far in
> [04:23] skies: Let’s see the outcome
> [04:23] freshererer: i wont eb mad if u remake
> [04:23] sidewalkill: fresh vote at least
> [04:23] freshererer: ok
> [04:23] Mission 1.5 was approved.
> [04:23] Chaos22 has left the room.
> [04:23] morningcatt: no dont lol
> [04:23] pmoomm: i dont want to remake im res
> [04:23] bb: remaking for what?
> [04:23] Mission 1 succeeded.
> [04:23] sidewalkill: i also dont want to rmk
> [04:24] sidewalkill: im res
> [04:24] freshererer: ok wait 5 mins then
> [04:24] morningcatt: chaos come back lmao
> [04:24] bb: I also don't want to remake
> [04:24] exmag: That's code for
> [04:24] sidewalkill: and my res WR needs boosting
> [04:24] bb: I'm spec
> [04:24] exmag: I'm a spy
> [04:24] sidewalkill: i like bb spec
> [04:24] Chaos22 has joined the room.
> [04:24] exmag has left the room.
> [04:24] sidewalkill: chaos pick
> [04:24] morningcatt has licked Chaos22. (In game)
> [04:24] skies: No remake my lab test isn’t over
> [04:24] sidewalkill: we give fresh 5 mins
> [04:24] Chaos22: BB is skipped
> [04:24] bb: I feel like this is what happens when I go bald and grey
> [04:24] skies: 5 min is too long tho
> [04:24] morningcatt has licked freshererer. (In game)
> [04:24] Chaos22: Why am I picking
> [04:24] exmag has joined the room.
> [04:24] pmoomm: bb is skipped
> [04:24] bb: LMFAO
> [04:24] morningcatt has licked sidewalkill. (In game)
> [04:24] sidewalkill: LMAOOOOOOOOOO
> [04:24] sidewalkill: BB HAS NO PICKS
> [04:24] morningcatt has licked pmoomm. (In game)
> [04:24] skies: What the tuck
> [04:24] Chaos22: Report bug
> [04:24] morningcatt has licked bb. (In game)
> [04:24] skies: Remake
> [04:24] morningcatt has licked skies. (In game)
> [04:24] pmoomm: hi catt
> [04:24] exmag: Bb is still speccing his own game
> [04:24] sidewalkill: wait i love this
> [04:24] Chaos22: I am assassin
> [04:24] sidewalkill: bb
> [04:24] Chaos22: I shoot skies
> [04:24] morningcatt: meow
> [04:24] sidewalkill: im merlin
> [04:24] skies: what happened
> [04:24] bb: Don't post it yet
> [04:24] sidewalkill: thanks bby
> [04:25] sidewalkill: the game is over
> [04:25] bb: Fuck
> [04:25] skies: I’m VT
> [04:25] sidewalkill: im merlin moom and chaos are spies
> [04:25] Chaos22: How df does skies call out pmoomm and myself 1.1
> [04:25] skies: Yay
> [04:25] bb: I'm gay
> [04:25] bb: And Merlin
> [04:25] sidewalkill: i love you skies for picking clean
> [04:25] sidewalkill: bc u didnt follow her gay meta
> [04:25] pmoomm: i hate you skies xD
> [04:25] skies: MY NEW META ROCKS
> [04:25] sidewalkill: LMAO
> [04:25] bb: Lolol
> [04:25] Chaos22: Okay so
> [04:25] sidewalkill: if she actually starts making us use this
> [04:25] Chaos22: Don't go uet
> [04:25] sidewalkill: its chaos and mooms fault
> [04:25] sidewalkill: yes we go i outed
> [04:25] Chaos22: I want to send screenshot to
> [04:25] Chaos22: Don't go
> [04:25] sidewalkill: oh yeah
> [04:25] sidewalkill: okay
> [04:25] sidewalkill: then i dont go
> [04:25] Chaos22: Just vote
> [04:25] Chaos22: In this one mission
> [04:25] skies: Lol the strat sucks btw
> [04:25] Chaos22 has picked: skies, freshererer, sidewalkill.
> [04:25] morningcatt: wow im slo bb got skippose
> [04:25] sidewalkill: ok so whats ur new meta
> [04:26] Chaos22: Just vote this one mission
> [04:26] bb: Lol
> [04:26] bb: Sure
> [04:26] Chaos22: I'm sending picture to pro of vh
> [04:26] sidewalkill: fresh doesnt vote anyway
> [04:26] pmoomm: fresh left
> [04:26] sidewalkill: so take pick of it blank
> [04:26] skies: Offpicking two res or two spies is disastrous
> [04:26] sidewalkill: *pic
> [04:26] Chaos22: This is a clean team
> [04:26] bb: Thanks vh is hilarious
> [04:26] bb: This*
> [04:26] Chaos22: Mhm
> [04:26] sidewalkill: this is why i play sh
> [04:26] Chaos22: Hey guys
> [04:26] sidewalkill: rmk?
> [04:26] bb: No bugs
> [04:26] Chaos22: Wanna play secret Hitler?
> [04:27] bb: No grubs
> [04:27] pmoomm: i can play
> [04:27] Chaos22: This is a weird bug
> [04:27] morningcatt: no
> [04:27] skies has left the room.
> [04:27] sidewalkill: no lol
> [04:27] bb has left the room.
> [04:27] Chaos22: SECRET HITLER LESGO
> [04:27] sidewalkill: sh is lame
> [04:27] morningcatt: not liket is
> [04:27] sidewalkill: bye
> [04:27] morningcatt has left the room.
> [04:27] pmoomm has left the room.
> [04:27] exmag has left the room.
> [04:27] skies has joined the room.
> [04:27] sidewalkill has left the room.
> [04:27] skies has left the room.
> [04:27] Chaos22 has left the room.
> [04:27] exmag has joined the room.
> [04:27] exmag has left the room.
> [04:28] Chaos22 has joined the room.
> [04:28] morningcatt has joined the room.
> [04:28] Chaos22 has left the room.
> [04:28] morningcatt has left the room.
> [04:30] Mission 2.1 was approved.
> [04:30] freshererer has left the room.
> [04:37] maddie has joined the room.
> [04:37] maddie has left the room.
> [04:38] anfoman has joined the room.
> [04:38] anfoman has left the room.
> [04:42] bocaben has joined the room.
> [04:54] bigz_200 has joined the room.
> [04:54] bigz_200 has left the room.
> [04:55] bless has joined the room.
> [04:55] bless has left the room.
> [04:55] CITC has joined the room.
> [04:55] CITC has left the room.
> [04:55] casshern has joined the room.
> [04:55] bless has joined the room.
> [04:56] bless has left the room.
> [04:56] casshern has left the room.

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
- N/A

**Comment by vck3000** [comment]
Closed as this has not happened in a long time.
