### ISSUE TITLE
Warning system 

### ISSUE THREAD

**Issue by vck3000** [vck3000/ProAvalon#71]
Each player should have a list of official warnings given to them. If a player has a warning and is warned again, a ban should be automatically made? Warnings can expire in 6 months or something. The idea is to help moderators keep track who was warned by who.

**Comment by bocaben** [comment]
i like the idea of a list of warnings / previous mutes and bans. i dont think automatic bans should be made though, but if you really want something like it, then give the mods a prompt recommending to ban them due to their history. auto-bans will cause more mistakes than help
