### ISSUE TITLE
Game options shows wrong number of max players if u seted it when created game

### ISSUE THREAD

**Issue by hakha3** [vck3000/ProAvalon#74]
**Describe the bug**
When you create game and set max players as something else than 10 and then when you first time try change it as host, in game options it says that max is 10, which makes that if you want change it back to 10, you need to choose different number than 10 and then 10 to make max 10 player

**To Reproduce**
1. Create game with 8 max players
2. Click on gear
3. See that it says max number of players: 10

**Expected behavior**
It should say correct max number of players

**Screenshots**
![2018-09-16](https://user-images.githubusercontent.com/43155373/45591257-df9c8f80-b94d-11e8-9791-d96bc2df6938.png)

**Comment by vck3000** [comment]
Fixed in #105.
