### ISSUE TITLE
Merlin? vs Merlin.

### ISSUE THREAD

**Issue by CottageInTheCity** [vck3000/ProAvalon#84]
When playing with Percival and without Morgana, Merlin still appears as "Merlin?". Should be simple enough to fix, and not really urgent at all.

**Comment by vck3000** [comment]
What to show if there is percival and morgana?

**Comment by CottageInTheCity** [comment]
> What to show if there is percival and morgana?

I'm not sure if you're misunderstanding me.
If Merlin and Morgana are in game, both appear as "Merlin?" to Percival
If Merlin is in the game without Morgana, he will still appear as "Merlin?" to Percival, instead of "Merlin."

**Comment by hakha3** [comment]
he means what if there isnt merlin, but are percival and morgana. Should he see her as merlin, merlin? or morgana.

**Comment by CottageInTheCity** [comment]
Ohhhhhhh. I say she should appear as "Morgana."

**Comment by vck3000** [comment]
Unnecessary?
