### ISSUE TITLE
Reskinning

### ISSUE THREAD

**Issue by CottageInTheCity** [vck3000/ProAvalon#85]
Instead of just having swords become those lame shields, how about we do more to Arthurianise (totally a word) the game for those that prefer the medieval tone:

Bland Shields --> [Colour Shields](https://cdn.discordapp.com/attachments/469884625796464658/488479706681704448/shield-orange.png)

Mission Leader Star --> [Crown](https://cdn.discordapp.com/attachments/469884625796464658/488480276901658634/elwJUQt.png)

Bullet from Assassin -->[Dagger](https://cdn.discordapp.com/attachments/469884625796464658/488560721567678465/dagger.png)

Previews:

[crown and shields on light theme](https://cdn.discordapp.com/attachments/419756401162715168/488570325965996032/unknown.png)

[crown and shields on dark theme](https://cdn.discordapp.com/attachments/419756401162715168/488570332148400129/unknown.png)

[dagger and shields on light theme](https://cdn.discordapp.com/attachments/419756401162715168/488575912728854539/unknown.png)

[dagger and shields on dark theme](https://cdn.discordapp.com/attachments/419756401162715168/488575917694779393/unknown.png)

**Comment by vck3000** [comment]
These look good!
