### ISSUE TITLE
Time Estimates in Ready Messaging

### ISSUE THREAD

**Issue by keleco** [vck3000/ProAvalon#88]
Can we add some messaging to the Ready popup to indicate the estimated game time?

Time estimates can be pulled from game stats,  and then massaged a bit to give a rough game time estimates.  Bocaben suggested using the middle 60 - 80% of games played to determine range.  This would knock off the extremes from the calculations

**Comment by vck3000** [comment]
Don't know if this is that worth it. We now have timer so should alleviate games stalling out forever.
