### ISSUE TITLE
Changes in server information that someone was buzzed/slapped in game

### ISSUE THREAD

**Issue by hakha3** [vck3000/ProAvalon#91]
There shouldnt be information about someone being buzzed/slapped in game if
-player wasnt buzzed/slapped
-buzzed player is spectator
-buzzing player is spectator

**Comment by vck3000** [comment]
Idk about the last one...

**Comment by keleco** [comment]
I dont know about the second one either

**Comment by keleco** [comment]
I don't know about the second one either.   It certainly isn't as big a risk for cheating as being able to buzz a player but in the true spirit of the game, all communication by players in game should be public.
