### ISSUE TITLE
Buzzing isnt working

### ISSUE THREAD

**Issue by hakha3** [vck3000/ProAvalon#93]
Sometimes buzzing isnt working. When someone buzzes me or I buzz myself I dont get any sound, but I get notification that Im buzzed. Once I turned on notification "player joining game" but I also dont get any sound notification.
"Test buzz" is working

EDIT:
But after server restart everything was ok, but its not first I experience this bug

**Comment by vck3000** [comment]
Needs more investigation for a cause.
