### ISSUE TITLE
Empty Forum Posts

### ISSUE THREAD

**Issue by bigz200** [vck3000/ProAvalon#96]
**Describe the bug**
Empty Forum Posts are allowed.

**To Reproduce**
1. Go to Forum
2. Click on 'Create'
3. Add a space into the Post Title
4. Click 'Submit'

**Screenshots**
![troll2](https://user-images.githubusercontent.com/36970195/46625334-3cc4d480-caf9-11e8-8a96-15e7fcb75fba.PNG)

**Expected behavior**
Error out or just not create post.

**Additional context**
There are aproxamatly 50 posts in there now by one user.

**Comment by vck3000** [comment]
Those posts have been removed. But we should fix this to not allow empty forums anyway. Or perhaps set a limit on how many new threads a user can create a day.

**Comment by bocaben** [comment]
Good idea - there should be a max thread per day, probably around 5. Deleting all those empty spam threads was tedious. Perhaps also add a mod feature to mass-delete all forum activity from a specific user from the last <specified> time. What do you think?

**Comment by vck3000** [comment]
Good ideas. Let's implement them.

**Comment by vck3000** [comment]
Fixed in 984a98b157f49ae2169436dc440b2d4690336417.
