### ISSUE TITLE
% sign in username makes their profile page generally inaccessible

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#98]
for example, when Mr100% clicks on his user profile, it sends him to
https://www.proavalon.com/profile/Mr100%

which is an invalid url due to the %

it should send him to:
https://www.proavalon.com/profile/Mr100%25
(%25 is the literal for "%")

for security concerns and to avoid this problem, i'd disallow all %'s and all ?'s in usernames as well

**Comment by vck3000** [comment]
Those characters are disallowed for new accounts, but not for existing users. Perhaps we should ask users to change accounts if they use it?

**Comment by bocaben** [comment]
If so, then please update the Registration Page to include those disallowed characters, since I didn't see them listed

**Comment by bocaben** [comment]
We can ask them, but we should have it fixed in the code too, since I don't know if it can lead to vulnerabilities. Probably very low priority though.
