### ISSUE TITLE
top menubar incomplete in mod pages

### ISSUE THREAD

**Issue by bocaben** [vck3000/ProAvalon#99]
https://www.proavalon.com/mod - missing Notifications and Settings buttons
https://www.proavalon.com/profile/mod/customavatar - missing Moderation and all the righthand buttons
https://www.proavalon.com/forum/page/1 - missing Moderation button

also, can there be 2 separate Mod tabs - one for the logs, the other for avatar requests? currently i need to go into the logs first and from there click to get to the avatar requests.

**Comment by vck3000** [comment]
Sounds good. Shouldn't be hard to do.

**Comment by bocaben** [comment]
Just don't forget to show the buttons mods can use only if the user is a actually a mod :)

**Comment by vck3000** [comment]
Implemented
